version: '3.8'

services:

  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: rimuru_memory
    ports:
      - "8080:8080"
    environment:
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - QUERY_DEFAULTS_LIMIT=25

  n8n:
    image: n8nio/n8n
    container_name: rimuru_orchestrator
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Paris
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=rimuru
    volumes:
      - rimuru_n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  rimuru_n8n_data: